import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:savvy_stock/core/widgets/custom_searchable_dropdown.dart';
import 'package:savvy_stock/features/system_constant/bloc/system_constant_bloc.dart';
import 'package:savvy_stock/features/system_constant/bloc/system_constant_event.dart';
import 'package:savvy_stock/features/system_constant/bloc/system_constant_state.dart';
import 'package:savvy_stock/core/widgets/custom_dropdown.dart';
import 'package:savvy_stock/core/widgets/custom_text_Form.dart';
import 'package:savvy_stock/features/auth/blocs/auth_bloc.dart';
import 'package:savvy_stock/features/stock/item_entry/blocs/item_entry_bloc.dart';
import 'package:savvy_stock/features/stock/item_entry/blocs/item_entry_event.dart';
import 'package:savvy_stock/features/stock/item_entry/blocs/item_entry_state.dart';
import 'package:savvy_stock/features/stock/item_entry/widgets/stock_qr_scanner.dart';
import 'package:savvy_stock/features/udc_detail/blocs/udc_detail_bloc.dart';
import 'package:savvy_stock/features/udc_detail/blocs/udc_detail_event.dart';
import 'package:savvy_stock/features/udc_detail/blocs/udc_detail_state.dart';
import 'package:savvy_stock/features/stock/item_entry/models/item_entry_model.dart';

class ItemEntryFormPage extends StatefulWidget {
  final ItemEntryModel? item;
  final AuthBloc authBloc;
  final bool isCreateInCreateMode;

  const ItemEntryFormPage({
    super.key,
    this.item,
    required this.authBloc,
    this.isCreateInCreateMode = false,
  });

  @override
  State<ItemEntryFormPage> createState() => _ItemEntryFormPageState();
}

class _ItemEntryFormPageState extends State<ItemEntryFormPage> {
  final _formKey = GlobalKey<FormState>();

  // Controllers
  final TextEditingController _itemsIdController = TextEditingController();
  final TextEditingController _itemDescriptionController =
      TextEditingController();
  final TextEditingController _barcodeController = TextEditingController();
  final TextEditingController _unitPriceController = TextEditingController();
  final TextEditingController _reorderPointController = TextEditingController();
  final TextEditingController _marginRateController = TextEditingController();

  String? _selectedMarginType;
  String? _selectedUom;
  String? _selectedTaxable;

  final List<String> _marginTypes = ['%', 'N']; // Flat or Percentage
  final List<String> _taxable = ['YES', 'NO'];

  @override
  void initState() {
    super.initState();
    _initializeControllers();

    // Load system constants
    context.read<SystemConstantBloc>().add(
      LoadSystemConstantsForCompany(widget.authBloc.state.companyId!),
    );

    // Load UoM details
    context.read<UdcDetailsBloc>().add(LoadUdcDetailsByGroup('UM'));

    // Set up item form if editing
    if (widget.item != null) {
      context.read<StockItemsEntryBloc>().add(SetItemForm(widget.item!));
    } else if (widget.isCreateInCreateMode) {
      // Prepare for create in create mode
      context.read<StockItemsEntryBloc>().add(PrepareCreateInCreate());
    }
  }

  void _initializeControllers() {
    final item = widget.item ?? ItemEntryModel.empty();

    _itemsIdController.text = item.itemsId ?? '';
    _itemDescriptionController.text = item.itemDescription ?? '';
    _barcodeController.text = item.barcode ?? '';

    _unitPriceController.text = item.unitPrice?.toString() ?? '';
    _reorderPointController.text = item.reorderPoint?.toString() ?? '';
    _marginRateController.text = item.marginRate?.toString() ?? '';

    _selectedMarginType = item.marginType;
    _selectedUom = item.unitOfMeasure;
    _selectedTaxable = item.taxable == 'Y'
        ? 'YES'
        : item.taxable == 'N'
        ? 'NO'
        : null;
  }

  // Helper method for safe number parsing
  double? _parseDouble(String value) {
    if (value.trim().isEmpty) return null;
    return double.tryParse(value.trim());
  }

  @override
  void dispose() {
    _itemsIdController.dispose();
    _itemDescriptionController.dispose();
    _barcodeController.dispose();
    _unitPriceController.dispose();
    _reorderPointController.dispose();
    _marginRateController.dispose();
    super.dispose();
  }

  void _saveItem() {
    if (_formKey.currentState!.validate()) {
      final systemConstantState = context.read<SystemConstantBloc>().state;
      final systemConstant = systemConstantState.systemConstant;

      String? finalBarcode = _barcodeController.text.trim();

      // Handle barcode generation based on system constant
      if (systemConstant?.generateBarcodeForItemBoolean == true) {
        if (finalBarcode.isEmpty) {
          // Barcode will be auto-generated by the bloc
          finalBarcode = null;
        }
      } else {
        if (finalBarcode.isEmpty) {
          finalBarcode = null;
        }
      }

      final item = ItemEntryModel(
        id: widget.item?.id ?? 0,
        itemsId: _itemsIdController.text.trim(),
        itemDescription: _itemDescriptionController.text.trim(),
        barcode: finalBarcode,
        unitPrice: _unitPriceController.text.trim().isEmpty
            ? null
            : _parseDouble(_unitPriceController.text),
        reorderPoint: _reorderPointController.text.trim().isEmpty
            ? null
            : _parseDouble(_reorderPointController.text),
        marginRate: _marginRateController.text.trim().isEmpty
            ? null
            : _parseDouble(_marginRateController.text),
        unitOfMeasure: _selectedUom,
        taxable: _selectedTaxable == 'YES' ? 'Y' : 'N',
        marginType: _selectedMarginType,
        company: widget.authBloc.state.companyId,
      );

      if (widget.item == null) {
        // Create new item
        if (widget.isCreateInCreateMode) {
          context.read<StockItemsEntryBloc>().add(SaveRowMain(item));
        } else {
          context.read<StockItemsEntryBloc>().add(SaveRow(item));
        }
      } else {
        // Update existing item
        context.read<StockItemsEntryBloc>().add(SaveRow(item));
      }

      _showSuccessDialog();
    }
  }

  void _showSuccessDialog() {
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (context) => BlocListener<StockItemsEntryBloc, ItemEntryState>(
        listener: (context, state) {
          if (state.status == ItemEntryStatus.success) {
            Navigator.of(context).pop();
            Navigator.of(context).pop(true); // Return success
          } else if (state.status == ItemEntryStatus.duplication) {
            Navigator.of(context).pop();
            _showErrorDialog(state.message ?? 'Duplicate item found');
          } else if (state.status == ItemEntryStatus.failure) {
            Navigator.of(context).pop();
            _showErrorDialog(state.message ?? 'An error occurred');
          }
        },
        child: AlertDialog(
          title: const Row(
            children: [
              CircularProgressIndicator(),
              SizedBox(width: 16),
              Text('Saving...'),
            ],
          ),
          content: const Text('Please wait while we save your item.'),
        ),
      ),
    );
  }

  void _showErrorDialog(String message) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Row(
          children: [
            Icon(Icons.error, color: Colors.red),
            SizedBox(width: 8),
            Text('Error'),
          ],
        ),
        content: Text(message),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('OK'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.item == null ? 'Create Item' : 'Edit Item'),
        backgroundColor: const Color(0xFF155888),
        foregroundColor: Colors.white,
        elevation: 0,
        actions: widget.item != null
            ? [
                IconButton(
                  icon: const Icon(Icons.delete),
                  onPressed: _deleteItem,
                  tooltip: 'Delete Item',
                ),
              ]
            : null,
      ),
      body: MultiBlocListener(
        listeners: [
          BlocListener<StockItemsEntryBloc, ItemEntryState>(
            listener: (context, state) {
              if (state.status == ItemEntryStatus.success &&
                  state.message?.contains('Saved') == true) {
                // Success is handled in the dialog
              } else if (state.status == ItemEntryStatus.failure) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text(state.message ?? 'An error occurred'),
                    backgroundColor: Colors.red,
                  ),
                );
              }
            },
          ),
          BlocListener<SystemConstantBloc, SystemConstantState>(
            listener: (context, state) {
              if (state.status == SystemConstantStatus.failure) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text(
                      state.errorMessage ?? 'System constant error',
                    ),
                    backgroundColor: Colors.red,
                  ),
                );
              }
            },
          ),
        ],
        child: Column(
          children: [
            _buildBarcodeInfo(),
            Expanded(child: _buildForm()),
            _buildBottomNavigation(),
            const SizedBox(height: 16),
          ],
        ),
      ),
    );
  }

  void _deleteItem() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Delete Item'),
        content: const Text('Are you sure you want to delete this item?'),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () {
              Navigator.of(context).pop();
              if (widget.item?.id != null) {
                context.read<StockItemsEntryBloc>().add(
                  DeleteItem(
                    itemId: widget.item!.id,
                    deletedItem: widget.item!,
                    deletedIndex: 0,
                  ),
                );
                Navigator.of(context).pop(true);
              }
            },
            child: const Text('Delete', style: TextStyle(color: Colors.red)),
          ),
        ],
      ),
    );
  }

  // Barcode information widget
  Widget _buildBarcodeInfo() {
    return BlocBuilder<SystemConstantBloc, SystemConstantState>(
      builder: (context, state) {
        final isAutoGenerateEnabled =
            state.selected?.generateBarcodeForItem == 'Y';
        print(isAutoGenerateEnabled);

        if (isAutoGenerateEnabled) {
          return Container(
            padding: const EdgeInsets.all(12),
            margin: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.blue[50],
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: Colors.blue[200]!),
            ),
            child: Row(
              children: [
                Icon(Icons.info, color: Colors.blue[600], size: 20),
                const SizedBox(width: 8),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Auto-barcode generation is ENABLED',
                        style: TextStyle(
                          color: Colors.blue[800],
                          fontSize: 12,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 2),
                      Text(
                        'Empty field will auto-generate EAN13 barcode',
                        style: TextStyle(color: Colors.blue[700], fontSize: 11),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          );
        } else {
          return Container(
            padding: const EdgeInsets.all(12),
            margin: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.orange[50],
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: Colors.orange[200]!),
            ),
            child: Row(
              children: [
                Icon(Icons.info, color: Colors.orange[600], size: 20),
                const SizedBox(width: 8),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Auto-barcode generation is DISABLED',
                        style: TextStyle(
                          color: Colors.orange[800],
                          fontSize: 12,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                      const SizedBox(height: 2),
                      Text(
                        'Empty field will be saved as empty',
                        style: TextStyle(
                          color: Colors.orange[700],
                          fontSize: 11,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          );
        }
      },
    );
  }

  Widget _buildBarcodeField() {
    return BlocBuilder<SystemConstantBloc, SystemConstantState>(
      builder: (context, state) {
        final isAutoGenerateEnabled =
            state.systemConstant?.generateBarcodeForItemBoolean == true;

        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            StockItemQRScanner(
              barcodeController: _barcodeController,
              onBarcodeScanned: (barcode) {
                // Handle the scanned barcode
                setState(() {
                  _barcodeController.text = barcode;
                });
              },
            ),
            const SizedBox(height: 8),
            if (isAutoGenerateEnabled && _barcodeController.text.isEmpty)
              Text(
                '• Leave empty for EAN13 auto-generation',
                style: TextStyle(fontSize: 12, color: Colors.green[700]),
              ),
          ],
        );
      },
    );
  }

  Widget _buildForm() {
    return Form(
      key: _formKey,
      child: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          children: [
            // Item ID
            CustomTextField(
              labelText: 'Item ID *',
              controller: _itemsIdController,
              validator: (value) {
                if (value == null || value.isEmpty) {
                  return 'Item ID is required';
                }
                return null;
              },
              onChanged: (value) {
                _itemsIdController.text = value;
              },
              prefixIcon: const Icon(Icons.numbers),
            ),
            const SizedBox(height: 16),
            // Description
            CustomTextField(
              labelText: 'Description *',
              controller: _itemDescriptionController,
              validator: (value) {
                if (value == null || value.isEmpty) {
                  return 'Description is required';
                }
                return null;
              },
              onChanged: (value) {
                _itemDescriptionController.text = value;
              },
              prefixIcon: const Icon(Icons.description),
            ),
            const SizedBox(height: 16),
            // Unit of Measure
            BlocBuilder<UdcDetailsBloc, UdcDetailsState>(
              builder: (context, state) {
                if (state.status == UdcDetailsStatus.loading) {
                  return const Center(child: CircularProgressIndicator());
                }
                if (state.groupCode == null || state.details.isEmpty) {
                  return const Padding(
                    padding: EdgeInsets.symmetric(vertical: 8.0),
                    child: Text(
                      'No UoM available',
                      style: TextStyle(color: Colors.grey),
                    ),
                  );
                }

                final items = state.details.toList();
                if (items.isEmpty) {
                  return const Padding(
                    padding: EdgeInsets.symmetric(vertical: 8.0),
                    child: Text(
                      'No valid UoM found',
                      style: TextStyle(color: Colors.grey),
                    ),
                  );
                }
                final itemDescriptions = state.details
                    .where((item) => item.description1.isNotEmpty)
                    .map((item) => item.description1)
                    .toSet()
                    .toList();

                return CustomSearchableDropdown(
                  labelText: 'Unit of Measure *',
                  value: _selectedUom?.toString(),
                  prefixIcon: Icons.scale,
                  options: itemDescriptions,
                  onChanged: (value) {
                    setState(() {
                      _selectedUom = value;
                    });
                  },
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Please select a Unit of Measure';
                    }
                    return null;
                  },
                );
              },
            ),
            const SizedBox(height: 16),
            // Unit Price
            CustomTextField(
              labelText: 'Unit Price',
              controller: _unitPriceController,
              keyboardType: TextInputType.numberWithOptions(decimal: true),
              onChanged: (value) {
                _unitPriceController.text = value;
              },
              prefixIcon: const Icon(Icons.attach_money),
            ),
            const SizedBox(height: 16),
            // Barcode
            _buildBarcodeField(),
            const SizedBox(height: 16),

            // Reorder Point
            CustomTextField(
              labelText: 'Reorder Point',
              controller: _reorderPointController,
              keyboardType: TextInputType.numberWithOptions(decimal: true),
              onChanged: (value) {
                _reorderPointController.text = value;
              },
              prefixIcon: const Icon(Icons.inventory_2),
            ),
            const SizedBox(height: 16),

            // Taxable
            CustomDropdown(
              labelText: 'Taxable',
              prefixIcon: const Icon(Icons.receipt),
              items: _taxable
                  .map(
                    (taxable) =>
                        DropdownMenuItem(value: taxable, child: Text(taxable)),
                  )
                  .toList(),
              value: _selectedTaxable,
              onChanged: (value) {
                setState(() {
                  _selectedTaxable = value;
                });
              },
            ),
            const SizedBox(height: 16),

            // Margin Type
            CustomDropdown(
              labelText: 'Margin Type',
              prefixIcon: const Icon(Icons.trending_up),
              items: _marginTypes
                  .map(
                    (marginType) => DropdownMenuItem(
                      value: marginType,
                      child: Text(marginType == '%' ? 'Percentage' : 'Flat'),
                    ),
                  )
                  .toList(),
              value: _selectedMarginType,
              onChanged: (value) {
                setState(() {
                  _selectedMarginType = value;
                });
              },
            ),
            const SizedBox(height: 16),

            // Margin Rate
            CustomTextField(
              labelText: 'Margin Rate',
              controller: _marginRateController,
              keyboardType: TextInputType.numberWithOptions(decimal: true),
              onChanged: (value) {
                _marginRateController.text = value;
              },
              prefixIcon: _selectedMarginType == '%'
                  ? const Icon(Icons.percent)
                  : const Icon(Icons.attach_money),
            ),
            const SizedBox(height: 16),
          ],
        ),
      ),
    );
  }

  Widget _buildBottomNavigation() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          // Back button
          ElevatedButton.icon(
            onPressed: () {
              Navigator.pop(context);
            },
            icon: const Icon(Icons.arrow_back, size: 20),
            label: const Text('Back'),
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.grey[300],
              foregroundColor: Colors.black87,
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(20),
              ),
            ),
          ),

          // Save button
          BlocBuilder<StockItemsEntryBloc, ItemEntryState>(
            builder: (context, state) {
              return ElevatedButton.icon(
                onPressed:
                    state.status == ItemEntryStatus.creating ||
                        state.status == ItemEntryStatus.updating
                    ? null
                    : _saveItem,
                icon:
                    state.status == ItemEntryStatus.creating ||
                        state.status == ItemEntryStatus.updating
                    ? const SizedBox(
                        width: 16,
                        height: 16,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          valueColor: AlwaysStoppedAnimation(Colors.white),
                        ),
                      )
                    : const Icon(Icons.save, size: 20),
                label: Text(
                  state.status == ItemEntryStatus.creating ||
                          state.status == ItemEntryStatus.updating
                      ? 'Saving...'
                      : 'Save',
                ),
                style: ElevatedButton.styleFrom(
                  backgroundColor: const Color(0xFF155888),
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.symmetric(
                    horizontal: 24,
                    vertical: 12,
                  ),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(20),
                  ),
                ),
              );
            },
          ),
        ],
      ),
    );
  }
}
