import 'package:savvy_stock/core/constants/app_routes.dart';

class PrivilegeRouteMapper {
  static const Map<int, String> _serverPrivilegeIdToAppRoute = {
    2: AppRoutes.adminDashboard,
    3: AppRoutes.salesCustomerInfo,
    4: AppRoutes.salesDashboard,
    5: AppRoutes.salesReview,
    6: AppRoutes.salesReview,
    7: AppRoutes.stockDashboard,
    16: AppRoutes.itemEntry,
    17: AppRoutes.branchManagement,
    18: AppRoutes.itemInBranch,
    20: AppRoutes.customerEntry,
    21: AppRoutes.employeeManagement,
    22: AppRoutes.systemConstants,
    24: AppRoutes.userManagement,
    25: AppRoutes.roleManagement,
    32: AppRoutes.companyManagement,
    33: AppRoutes.companyCreation,
    34: AppRoutes.companyEdit,
    36: AppRoutes.roleEdit,
    37: AppRoutes.roleCreation,
    38: AppRoutes.employeeCreation,
    39: AppRoutes.employeeEdit,
    43: AppRoutes.branchCreation,
    44: AppRoutes.userCreation,
    45: AppRoutes.userEdit,
    47: AppRoutes.customerCreate,
    48: AppRoutes.customerEdit,
    49: AppRoutes.purchaseReview,
    50: AppRoutes.purchaseSupplierInfo,
    52: AppRoutes.purchaseReview,
    53: AppRoutes.purchaseOrderReceive,
    54: AppRoutes.creditPurchaseReview,
    55: AppRoutes.salesCreditReceiptReview,
    56: AppRoutes.supplierEntry,
    57: AppRoutes.supplierCreate,
    58: AppRoutes.supplierEdit,
    60: AppRoutes.itemUomConversions,
    61: AppRoutes.purchaseItemEntry,
    63: AppRoutes.inventoryTransactionCreate,
    64: AppRoutes.inventoryTransaction,
    66: AppRoutes.creditPaymentReport,
    67: AppRoutes.itemInBranchAvailability,
    68: AppRoutes.creditRecievedReport,
    69: AppRoutes.locationEntry,
    70: AppRoutes.locationMasterCreate,
    71: AppRoutes.locationMasterEdit,
    72: AppRoutes.itemInLocationAvailability,
    73: AppRoutes.lotEntry,
    74: AppRoutes.lotColorings,
    75: AppRoutes.itemInLotAvailability,
    82: AppRoutes.itemCreation,
    83: AppRoutes.itemEdit,
    84: AppRoutes.salesDashboard,
    86: AppRoutes.itemWorkbench,
    87: AppRoutes.itemWorkbenchSingleCreate,
    88: AppRoutes.branchCreation,
    95: AppRoutes.purchaseDashboard,
    97: AppRoutes.salesTransactionReport,
    98: AppRoutes.salesReport,
    100: AppRoutes.purchaseReport,
    101: AppRoutes.stockReport,
    103: AppRoutes.cashFlowReport,
    104: AppRoutes.reportDashboard,
    105: AppRoutes.purchaseTransactionReport,
    107: AppRoutes.goodsReceivedNote,
    109: AppRoutes.creditPaymentReport,
    110: AppRoutes.agedCreditPaymentReceiptReport,
    111: AppRoutes.salesTransactionReport,
    113: AppRoutes.cashFlowSummaryReport,
    114: AppRoutes.cashInFlowReport,
    115: AppRoutes.cashOutFlowReport,
    117: AppRoutes.itemCostReport,
    118: AppRoutes.inventoryTransactionReport,
    119: AppRoutes.reorderPointReport,
    121: AppRoutes.inventoryMovementReport,
    124: AppRoutes.salesReturnDashboard,
    125: AppRoutes.salesCreditReceiptReview,
    127: AppRoutes.expirationReport,
    128: AppRoutes.salesReport,
    129: AppRoutes.uomManagement,
    130: AppRoutes.agedCreditSalesReport,
    132: AppRoutes.quotationOrderReview,
    136: AppRoutes.quotationOrder,
    134: AppRoutes.pendingPurcahseReport,
    135: AppRoutes.creditRecievedReport,
    137: AppRoutes.upcomingExpirationReport,
    139: AppRoutes.licenseDetails,
    143: AppRoutes.dailyStockReport,
    146: AppRoutes.otherExpenses,
  };

  static String toAppRoute({required int id, required String serverRoute}) {
    return _serverPrivilegeIdToAppRoute[id] ?? serverRoute;
  }
}
